; ============================================
; T_motor   = tiempo que tarda en encender motores 
; T_pista   = tiempo rodando en pista antes de rotar
; T_rotar   = cuanto tiempo jalas el morro al despegar
; T_subida  = tiempo subiendo antes de nivelar
; T_vuelo   = tiempo en crucero
; T_bajar   = tiempo bajando en descenso
; T_final   = tiempo en aproximacion final
; T_flare   = cuanto tiempo jalas en el flare antes de tocar
; T_freno   = tiempo frenando en pista
; flaps_dep = cuantas posiciones de flap para despegar
; flaps_ate = cuantas posiciones de flap para aterrizar
; tren      = 1: si el avion tiene tren retractil, 0: si no
; spoilers  = 1: si el avion tiene spoilers, 0: si no
; X_v1/Y_v1 = posicion de la valvula izquierda (se llena solo la primera vez)
; X_v2/Y_v2 = posicion de la valvula derecha   
; ============================================


[Boeing737]
T_pista=10000
T_rotar=5000
T_subida=12000
T_vuelo=50000
T_bajar=12000
T_final=6000
T_flare=2000
T_freno=6000
T_accel=10000
flaps_dep=2
flaps_ate=3
tren=1
spoilers=1
autopilot=1

[Cessna172]
T_pista=8000
T_rotar=4000
T_subida=10000
T_vuelo=50000
T_bajar=10000
T_final=5000
T_flare=1500
T_freno=4000
T_accel=10000
flaps_dep=1
flaps_ate=2
tren=0
spoilers=0
autopilot=0

[PiperCub]
T_pista=7000
T_rotar=3000
T_subida=8000
T_vuelo=50000
T_bajar=8000
T_final=4000
T_flare=1200
T_freno=3000
T_accel=10000
flaps_dep=0
flaps_ate=0
tren=0
spoilers=0
autopilot=0